
[functions.parse-invoice-edge]
enabled = true
verify_jwt = true
import_map = "./functions/parse-invoice-edge/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-invoice-edge/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-invoice-edge/*.html" ]
